### ISSUE TITLE
Github actions failing to log into azure

### ISSUE THREAD

**Issue by AnotherDaphne** [AnotherDaphne/cosi-103a#134]
The only part of the automation for github actions that fails is the step to log into azure. The error given says:

Login failed with Error: Using auth-type: SERVICE_PRINCIPAL. Not all values are present. Ensure 'client-id' and 'tenant-id' are supplied.. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.

The auth-type used and we double checked client id and tenant id being correct.
The link the error says to reference says that none of these input parameters are required to log in, but it still isn't working. 

We are unsure about where to go from here.

**Comment by yuh2k** [comment]
Hi Daphne,

Could you please check the environment of your github repo, to see if there's something called "prd" here

<img width="752" alt="image" src="https://github.com/AnotherDaphne/cosi-103a/assets/48446719/2b9e3992-8ad6-4d8f-8647-d12d5ebd2ddf">

**Comment by yuh2k** [comment]
Also I am tring on my end so if you may recieve multiple pipeline failed notifications, but you could mute it!

**Comment by yuh2k** [comment]
Good news it's running on my branch

Successful run: https://github.com/AnotherDaphne/cosi-103a/actions/runs/8442445848

Here are things you need take care of:

1.  In my branch, I tried to hardcode those key ids to make sure thay are identical to the Azure setting: https://github.com/AnotherDaphne/cosi-103a/blob/yuh2k-ci/.github/workflows/main.yml. But it's definitely not a good practice. Just double check they are the same wtih your environment

2.    For this part:
`  deploy-infra:
    needs: build
    runs-on: ubuntu-latest
    environment: prd`
    
    make sure the env name is same as your github env name

3. Change name to **resourceGroup:** cosi103-a, it should be also as same as: https://portal.azure.com/?feature.msaljs=true#@brandeis.edu/resource/subscriptions/aa8cd2f3-bd4c-432d-827a-bcf15d38cbbd/resourceGroups/cosi-103a/overview


4. You may just copy and paste my main.yaml to your main branch, just change the  branches name and  replace those hardcodings.


I hope it's also good on your ends
